# Generated by Django 5.2 on 2025-04-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='featured_exhibitions/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='upcoming_exhibitions/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='fashionitem',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('experimental-silhouettes', 'Experimental Silhouettes'), ('futuristic-couture', 'Futuristic Couture'), ('abstract-fusion', 'Abstract Fusion'), ('urban-casual', 'Urban Casual'), ('graffiti-inspired', 'Graffiti-Inspired'), ('skate-culture', 'Skate Culture'), ('runway-elegance', 'Runway Elegance'), ('opulent-craftsmanship', 'Opulent Craftsmanship'), ('timeless-luxury', 'Timeless Luxury'), ('eco-friendly-designs', 'Eco-Friendly Designs'), ('recycled-materials', 'Recycled Materials'), ('green-couture', 'Green Couture'), ('free-spirited-flow', 'Free-Spirited Flow'), ('desert-vibes', 'Desert Vibes'), ('gypsy-aesthetic', 'Gypsy Aesthetic'), ('clean-lines', 'Clean Lines'), ('monochrome-elegance', 'Monochrome Elegance'), ('pure-simplicity', 'Pure Simplicity'), ('retro-revival', 'Retro Revival'), ('classic-flair', 'Classic Flair'), ('old-hollywood-glam', 'Old Hollywood Glam')], max_length=100),
        ),
    ]
